version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  flask:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - CHATGPT_API_KEY=sk-...
      - JWT_SECRET_KEY=YOUR_SECRET_KEY_HERE
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=8080
      - MONGODB_URL=mongodb://mongo:27017/
    depends_on:
      - mongo
    links:
      - mongo
  react:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    depends_on:
      - flask
